/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuCreditos2.java
 *
 * Created on 21/11/2011, 00:11:04
 */
package game.gui.menus;

import game.gui.GameContainer;
import game.gui.StatePanel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Lucas Aoki
 */
public class MenuCredits extends StatePanel implements KeyListener {
    private GameContainer gc;
    
    /** Creates new form MenuCreditos2 */
    public MenuCredits(GameContainer gc) {
        super(640, 480);
        this.gc = gc;
        initComponents();
        
        gc.getMainFrame().addKeyListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        backButton.setFont(new java.awt.Font("Lithos Pro Regular", 0, 18));
        backButton.setText("BACK");
        backButton.setFocusable(false);
        jPanel1.add(backButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int keyTyped = e.getKeyCode();
        if (keyTyped == KeyEvent.VK_ENTER) {
            gc.setGameState(GameContainer.State.MENUSTATE);
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
