/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerSelectionPanel.java
 *
 * Created on 20/11/2011, 10:12:18
 */
package game.gui.menus;

import game.component.render.ImageRenderComponent;
import game.entity.Entity;
import game.gui.GameContainer;
import game.gui.StatePanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Lucas Aoki
 */
public class PlayerSelectionPanel extends StatePanel implements KeyListener, ActionListener {

    int choice = 0;
    GameContainer gc = null;

    /** Creates new form PlayerSelectionPanel */
    public PlayerSelectionPanel(GameContainer gc) {
        super(gc);
        initComponents();

        this.gc = gc;

        entities.add(new Entity("Background"));
        getEntity("Background").addComponent(new ImageRenderComponent("bGround", "/images/backgrounds/basicbackground.jpg"));

        gc.getMainFrame().addKeyListener(this);

        kenshinSelect.addActionListener(this);
        hieiSelect.addActionListener(this);
        ichigoSelect.addActionListener(this);
        zoroSelect.addActionListener(this);
        confirm.addActionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        kenshinSelect = new javax.swing.JToggleButton();
        hieiSelect = new javax.swing.JToggleButton();
        ichigoSelect = new javax.swing.JToggleButton();
        zoroSelect = new javax.swing.JToggleButton();
        confirm = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        kenshinSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kenshinselect.png"))); // NOI18N
        kenshinSelect.setSelected(true);
        kenshinSelect.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(kenshinSelect, gridBagConstraints);

        hieiSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hieiselect.png"))); // NOI18N
        hieiSelect.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(hieiSelect, gridBagConstraints);

        ichigoSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ichigoselect.png"))); // NOI18N
        ichigoSelect.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(ichigoSelect, gridBagConstraints);

        zoroSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoroselect.png"))); // NOI18N
        zoroSelect.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        add(zoroSelect, gridBagConstraints);

        confirm.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18));
        confirm.setText("Continuar");
        confirm.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(confirm, gridBagConstraints);

        title.setFont(new java.awt.Font("AR JULIAN", 0, 36)); // NOI18N
        title.setText("Player Selection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 60, 0);
        add(title, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JToggleButton hieiSelect;
    private javax.swing.JToggleButton ichigoSelect;
    private javax.swing.JToggleButton kenshinSelect;
    private javax.swing.JLabel title;
    private javax.swing.JToggleButton zoroSelect;
    // End of variables declaration//GEN-END:variables

    public void setChoice() {
        switch (choice) {
            case 0:
                kenshinSelect.setSelected(true);
                hieiSelect.setSelected(false);
                ichigoSelect.setSelected(false);
                zoroSelect.setSelected(false);
                break;
            case 1:
                kenshinSelect.setSelected(false);
                hieiSelect.setSelected(true);
                ichigoSelect.setSelected(false);
                zoroSelect.setSelected(false);
                break;
            case 2:
                kenshinSelect.setSelected(false);
                hieiSelect.setSelected(false);
                ichigoSelect.setSelected(true);
                zoroSelect.setSelected(false);
                break;
            case 3:
                kenshinSelect.setSelected(false);
                hieiSelect.setSelected(false);
                ichigoSelect.setSelected(false);
                zoroSelect.setSelected(true);
                break;
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object src = e.getSource();
        if (src == kenshinSelect) {
            choice = 0;
        }
        if (src == hieiSelect) {
            choice = 1;

        }
        if (src == ichigoSelect) {
            choice = 2;

        }
        if (src == zoroSelect) {
            choice = 3;
        }
        if (src == confirm) {
            gc.setChoice(choice);
            gc.setGameState(GameContainer.State.GAMESTATE);
        }
        setChoice();

    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        int keyTyped = e.getKeyCode();
        if (keyTyped == KeyEvent.VK_RIGHT) {
            if (choice < 4) {
                choice++;
            }
        }
        if (keyTyped == KeyEvent.VK_LEFT) {
            if (choice > 0) {
                choice--;
            }
        }
        if (keyTyped == KeyEvent.VK_ENTER) {
            gc.setChoice(choice);
            gc.setGameState(GameContainer.State.GAMESTATE);
        }
        setChoice();
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
}
